import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="relative bg-black">
        {children}
        <div className="absolute bottom-0 left-0 right-0 z-10 mt-[80px] p-5 text-center text-[13px] tracking-widest text-white/60 md:mt-[200px]">
          © 2023 Mist. All rights reserved.
        </div>
      </body>
    </html>
  );
}
