import BgVideo from "./components/common/bgVideo";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="relative bg-black">
        <BgVideo />
        <button className="absolute right-0 top-0 flex h-[80px] md:h-[100px] w-[100px] md:w-[145px] flex-col items-center justify-center gap-2.5 z-50">
          <span className="md:h-[3px] h-0.5 w-[40px] md:w-[65px] bg-white"></span>
          <span className="md:h-[3px] h-0.5 w-[40px] md:w-[65px] bg-white"></span>
        </button>
        {children}
        <div className="absolute bottom-0 left-0 right-0 z-10 mt-[80px] p-5 text-center text-[13px] tracking-widest text-white/60 md:mt-[200px]">
          © 2023 Mist. All rights reserved.
        </div>
      </body>
    </html>
  );
}
