import Header from './components/header/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[url('/bg-deco.png')] bg-right-top bg-no-repeat">
        <Header />
        {children}
      </body>
    </html>
  )
}
